version: '2.2'

services:
  valley:
    restart: unless-stopped
    build:
      args:
        STEAM_USER: "username"
        STEAM_LOGIN_KEY: "qwerty123456"
    container_name: stardew
    environment:
      - ALWAYS_ON_SERVER_UPGRADE_HOUSE=3
      - ALWAYS_ON_SERVER_PET_NAME=CAILSNOCK
      - ALWAYS_ON_SERVER_COPY_INVITE_CODE_TO_CLIPBOARD=true
      - ALWAYS_ON_SERVER_LOCK_PLAYER_CHESTS=false
      - UNLIMITED_PLAYERS_PLAYER_LIMIT=20
      - ENABLE_CHATCOMMANDS_MOD=true
      - ENABLE_CONSOLECOMMANDS_MOD=true
      - ENABLE_CROPSANYTIMEANYWHERE_MOD=true
      - ENABLE_FRIENDSFOREVER_MOD=true
      - ENABLE_NOFENCEDECAY_MOD=true
      - ENABLE_NONDESTRUCTIVENPCS_MOD=true